### PR TITLE
Four new domains and then even more.

### PR DESCRIPTION
**Pull request by Kezxo**

### CODE REVIEW

**Comment by vavavr00m** [comment]
@Kezxo it's missing the ff:

35.190.91.111
35.201.98.64

**Comment by Kezxo** [comment]
@vavavr00m you're right, they changed the page. Thanks for the IP's.

**Comment by vavavr00m** [comment]
35.201.103.212
35.186.249.84

are these two included?

**Comment by Kezxo** [comment]
I didn't search those before but I did now, no new domains though.
Sure, I can delete those.

**Comment by vavavr00m** [comment]
How do you gather these new ones?

**Comment by Kezxo** [comment]
Searching urlscan for existing hashes and IP's from the old ones.

**Pull request merged**
